import type { ReleaseSurfaceDriverRequest } from "../lib/release-surface-driver-protocol";

type Assignment = ReleaseSurfaceDriverRequest["assignments"][number];

export const UI_CONTROL_BOUNDED_INSTALLED_DRIVER_ID = "ui-control-bounded-installed";

/**
 * Generic UI cohorts whose complete dispatch path uses native input, bounded
 * element observations, and authenticated Debug API fixtures only. Keep this
 * exact allowlist fail-closed: families that still require unbounded renderer
 * scripts remain assigned to the generic building-on-macOS driver.
 */
export const UI_CONTROL_BOUNDED_INSTALLED_SURFACE_NAMES = new Set([
  'src/components/DebugApiConnectionBanner.tsx:[data-debug-id="debug-api-retry"]',
  'src/components/ErrorBoundary.tsx:role=button;name="Reload window"',
  'src/components/ErrorBoundary.tsx:role=button;name="Reset UI"',
  'src/App.tsx:[aria-label="Download Grok session artifacts"]',
  'src/App.tsx:[data-debug-id="remote-cwd-close"]',
  'src/App.tsx:[data-debug-id="remote-cwd-folder"]',
  'src/App.tsx:[data-debug-id="remote-cwd-go"]',
  'src/App.tsx:[data-debug-id="remote-cwd-input"]',
  'src/App.tsx:[data-debug-id="remote-cwd-parent"]',
  'src/App.tsx:[data-debug-id="remote-cwd-up"]',
  'src/App.tsx:[data-debug-id="remote-cwd-use"]',
  'src/browser/components/AgentSidebar.tsx:[data-debug-id="shellx-browser-collapse-console"]',
  'src/browser/components/AgentSidebar.tsx:[data-debug-id="shellx-browser-collapse-receipts"]',
  'src/browser/components/AgentSidebar.tsx:[data-debug-id="shellx-browser-collapse-tasks"]',
  'src/browser/components/AgentSidebar.tsx:[data-debug-id="shellx-browser-agent-abort"]',
  'src/browser/components/AgentSidebar.tsx:[data-debug-id="shellx-browser-agent-pause"]',
  'src/browser/components/AgentSidebar.tsx:[data-debug-id="shellx-browser-agent-resume"]',
  'src/browser/components/AgentSidebar.tsx:[data-debug-id="shellx-browser-agent-takeover"]',
  'src/browser/components/AgentSidebar.tsx:[data-debug-id="shellx-browser-block"]',
  'src/browser/components/AgentSidebar.tsx:[data-debug-id="shellx-browser-complete"]',
  'src/browser/components/AgentSidebar.tsx:[data-debug-id="shellx-browser-goal"]',
  'src/browser/components/AgentSidebar.tsx:[data-debug-id="shellx-browser-right-tab-actions"]',
  'src/browser/components/AgentSidebar.tsx:[data-debug-id="shellx-browser-right-tab-chat"]',
  'src/browser/components/AgentSidebar.tsx:[data-debug-id="shellx-browser-right-tab-errors"]',
  'src/browser/components/AgentSidebar.tsx:[data-debug-id="shellx-browser-right-tab-evidence"]',
  'src/browser/components/AgentSidebar.tsx:[data-debug-id="shellx-browser-right-tab-requests"]',
  'src/browser/components/AgentSidebar.tsx:[data-debug-id="shellx-browser-sidebar-resize"]',
  'src/browser/components/AgentSidebar.tsx:[data-debug-id="shellx-browser-toggle-right-sidebar-button"]',
  'src/browser/components/BookmarkSidecar.tsx:[data-debug-id="shellx-browser-bookmark-manager-close"]',
  'src/browser/components/BookmarkSidecar.tsx:[data-debug-id="shellx-browser-bookmark-list-mode"]',
  'src/browser/components/BookmarkSidecar.tsx:[data-debug-id="shellx-browser-bookmark-manager-toggle"]',
  'src/browser/components/BookmarkSidecar.tsx:[data-debug-id="shellx-browser-bookmark-draft-label"]',
  'src/browser/components/BookmarkSidecar.tsx:[data-debug-id="shellx-browser-bookmark-draft-url"]',
  'src/browser/components/BookmarkSidecar.tsx:[data-debug-id="shellx-browser-bookmark-draft-folder"]',
  'src/browser/components/BookmarkSidecar.tsx:[data-debug-id^="shellx-browser-bookmark-drag-"]',
  'src/browser/components/BookmarkSidecar.tsx:[data-debug-id^="shellx-browser-bookmark-label-"]',
  'src/browser/components/BookmarkSidecar.tsx:[data-debug-id^="shellx-browser-bookmark-url-"]',
  'src/browser/components/BookmarkSidecar.tsx:[data-debug-id^="shellx-browser-bookmark-pin-"]',
  'src/browser/components/BookmarkSidecar.tsx:[data-debug-id^="shellx-browser-bookmark-delete-"]',
  'src/browser/components/BookmarkSidecar.tsx:[aria-label="New folder"]',
  'src/browser/components/BookmarkSidecar.tsx:[aria-label="Add link"]',
  'src/browser/components/BookmarkSidecar.tsx:[data-debug-id^="shellx-browser-bookmark-"]',
  'src/browser/components/BookmarkSidecar.tsx:[data-debug-id="surface-browser-components-bookmarksidecar-5"]',
  'src/browser/components/BookmarkToolbar.tsx:[data-debug-id^="shellx-browser-bookmark-folder-"]',
  'src/browser/components/BookmarkToolbar.tsx:[data-debug-id^="shellx-browser-bookmark-toolbar-link-"]',
  'src/browser/components/BookmarkToolbar.tsx:[data-debug-id^="shellx-browser-bookmark-folder-child-"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-ad-mode-balanced"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-ad-mode-default"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-ad-mode-off"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-ad-mode-strict"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-color-mode"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-homepage"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-options-close"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-parallel-agents"]',
  'src/browser/components/BrowserMenus.tsx::is([data-debug-id="shellx-browser-personal-enable-now"],[data-debug-id="shellx-browser-personal-lock-now"],[data-debug-id="shellx-browser-personal-unlock-now"])',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-personal-lock-auth-mode"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-personal-lock-blur"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-personal-lock-enabled"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-personal-lock-minimize"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-personal-lock-pause-delegated"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-personal-lock-pin"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-personal-lock-set-pin"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-personal-lock-sleep"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-personal-lock-timeout"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-profile-select"]',
  'src/browser/components/BrowserMenus.tsx:[data-debug-id="shellx-browser-toggle-right-sidebar"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-ad-filter"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-address"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id^="shellx-browser-tab-"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id^="shellx-browser-close-tab-"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-back"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-bookmarks-menu"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-bookmark-current"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-downloads-menu"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-forward"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-handoff-tab"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-history-menu"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-home"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-lock-tab"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-new-disposable-tab"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-new-tab"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-options"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-personal-lock-toggle"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-reload"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-save-page"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-show-right-sidebar-button"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-take-back-tab"]',
  'src/browser/components/BrowserChrome.tsx:[data-debug-id="shellx-browser-trust-chip"]',
  'src/browser/components/BrowserHistorySidecar.tsx:[data-debug-id="shellx-browser-history-close"]',
  'src/browser/components/BrowserHistorySidecar.tsx:[data-debug-id="shellx-browser-clear-history"]',
  'src/browser/components/BrowserHistorySidecar.tsx:[data-debug-id="shellx-browser-history-date-filter"]',
  'src/browser/components/BrowserHistorySidecar.tsx:[data-debug-id^="shellx-browser-history-entry-"]',
  'src/browser/components/BrowserHistorySidecar.tsx:[data-debug-id="shellx-browser-history-agent"]',
  'src/browser/components/BrowserHistorySidecar.tsx:[data-debug-id="shellx-browser-history-user"]',
  'src/browser/components/BrowserHistorySidecar.tsx:[data-debug-id="shellx-browser-history-search"]',
  'src/browser/components/DownloadSidecar.tsx:[data-debug-id="shellx-browser-download-folder"]',
  'src/browser/components/DownloadSidecar.tsx:[data-debug-id="shellx-browser-downloads-close"]',
  'src/browser/components/BrowserEvidencePanel.tsx:[data-debug-id="shellx-browser-evidence-record"]',
  'src/browser/components/BrowserEvidencePanel.tsx:[data-debug-id="shellx-browser-evidence-refresh"]',
  'src/components/ActivityBrowserModal.tsx:[data-debug-id="activity-tab-evidence"]',
  'src/components/ActivityBrowserModal.tsx:[data-debug-id="activity-tab-files"]',
  'src/components/ActivityBrowserModal.tsx:[data-debug-id="activity-tab-graph"]',
  'src/components/ActivityBrowserModal.tsx:[data-debug-id="activity-tab-summary"]',
  'src/components/ActivityBrowserModal.tsx:[data-debug-id="activity-tab-timeline"]',
  'src/components/ActivityBrowserModal.tsx:[data-debug-id^="activity-evidence-section-"][data-debug-id$="-expand"]',
  'src/components/ActivityBrowserModal.tsx:[data-debug-id="activity-search"]',
  'src/components/ActivityBrowserModal.tsx:[data-debug-id="activity-search-clear"]',
  'src/components/AttachmentMediaBoard.tsx:[data-debug-id="surface-components-attachmentmediaboard-9"]',
  'src/components/AttachmentMediaBoard.tsx:[aria-label="Preview file"]',
  'src/components/AttachmentMediaBoard.tsx:[aria-label="Remove attachment"]',
  'src/components/AttachmentMediaBoard.tsx:[data-debug-id="surface-components-attachmentmediaboard-12"]',
  'src/components/AttachmentMediaBoard.tsx:[data-debug-id="surface-components-attachmentmediaboard-14"]',
  'src/components/AttachmentMediaBoard.tsx:[aria-label^="Preview "]',
  'src/components/AttachmentMediaBoard.tsx:[aria-label^="Attach "]',
  'src/components/AttachmentMediaBoard.tsx:[aria-label^="Import "]',
  'src/components/AttachmentMediaBoard.tsx:[data-debug-id="surface-components-attachmentmediaboard-18"]',
  'src/components/AttachmentMediaBoard.tsx:[data-debug-id="surface-components-attachmentmediaboard-19"]',
  'src/components/AttachmentMediaBoard.tsx:role=button;name="Inspect"',
  'src/components/AttachmentMediaBoard.tsx:role=button;name="Summarize"',
  'src/components/AttachmentMediaBoard.tsx:role=button;name="Find"',
  'src/components/MediaPreview.tsx:[data-debug-id="surface-components-mediapreview-1"]',
  'src/components/BottomPanel.tsx:role=button;name="Find"',
  'src/components/AgentRunsMonitor.tsx:[data-debug-id="tasks-agent-runs-refresh"]',
  'src/components/BuiltinDocModal.tsx:[aria-label="Close (Esc)"]',
  'src/components/BottomPanel.tsx:[data-debug-id="composer-prompt"]',
  'src/components/BuildPlanReviewModal.tsx:[aria-label="Review later"]',
  'src/components/BuildPlanReviewModal.tsx:[data-debug-id="surface-components-buildplanreviewmodal-4"]',
  'src/components/BuildPlanReviewModal.tsx:[data-debug-id="surface-components-buildplanreviewmodal-5"]',
  'src/components/BuildPlanReviewModal.tsx:role=button;name="Review later"',
  'src/components/BuildRunCockpit.tsx::is([title="Reconnect this tab and resume Build Mode auto-continuation."],[title="Resume Build Mode auto-continuation."])',
  'src/components/BuildRunCockpit.tsx:[title="Approve the Build Mode scratchboard and start execution."]',
  'src/components/BuildRunCockpit.tsx:[title="Create a local shellX git checkpoint and attach it to this Build Mode run."]',
  'src/components/BuildRunCockpit.tsx:[title="Pause Build Mode auto-continuation."]',
  'src/components/BuildRunCockpit.tsx:[title="Recheck blocker evidence without restarting or prompting the Agent."]',
  'src/components/BuildRunCockpit.tsx:[title="Reject this Build Mode plan and halt the run."]',
  'src/components/BuildRunCockpit.tsx:[title="Stop Build Mode manually without accepting completion."]',
  'src/components/BuildRunCockpit.tsx::is([title="Show every receipt in this Build Mode run"],[title="Show latest receipts only"])',
  'src/components/CommandPalette.tsx:[data-debug-id="command-palette-input"]',
  'src/components/CommandPalette.tsx:[data-debug-id="surface-components-commandpalette-4"]',
  'src/components/ConnectorInboxModal.tsx:[data-debug-id="connector-inbox-date-input"]',
  'src/components/ConnectorInboxModal.tsx:[data-debug-id="connector-inbox-search-input"]',
  'src/components/ConnectorInboxModal.tsx:[data-debug-id="surface-components-connectorinboxmodal-4"]',
  'src/components/ConnectorInboxModal.tsx:[data-debug-id="surface-components-connectorinboxmodal-9"]',
  'src/components/ConnectorInboxModal.tsx:role=button;name="Clear"',
  'src/components/ConnectorInboxModal.tsx:role=button;name="Connectors settings"',
  'src/components/ConnectionEditor.tsx:[aria-label="Cancel connection changes"]',
  'src/components/ConnectionEditor.tsx:[aria-label="Close connection editor"]',
  'src/components/ConnectionEditor.tsx:[data-debug-id="connection-label-input"]',
  'src/components/ConnectionEditor.tsx:[data-debug-id="connection-ssh-host-input"]',
  'src/components/ConnectionEditor.tsx:[data-debug-id="connection-ssh-key-select"]',
  'src/components/ConnectionEditor.tsx:[data-debug-id="connection-ssh-port-input"]',
  'src/components/ConnectionEditor.tsx:[data-debug-id="connection-ssh-runtime-select"]',
  'src/components/ConnectionEditor.tsx:[data-debug-id="connection-ssh-wsl-distro-input"]',
  'src/components/ConnectionEditor.tsx:[data-debug-id="connection-transport-local"]',
  'src/components/ConnectionEditor.tsx:[data-debug-id="connection-transport-ssh"]',
  'src/components/ConnectionEditor.tsx:[data-debug-id="connection-transport-wsl"]',
  'src/components/ConnectionEditor.tsx:[data-debug-id="connection-wsl-distro-input"]',
  'src/components/ConnectionPicker.tsx:[title="Add a new connection"]',
  'src/components/settings/ConnectionsTab.tsx:[title="Add a new connection preset"]',
  'src/components/RightRail.tsx:role=button;name="Notes"',
  'src/components/RightRail.tsx:role=button;name="Check"',
  'src/components/RightRail.tsx:role=button;name="Install"',
  'src/components/RightRail.tsx:[data-debug-id="surface-components-rightrail-2"]',
  'src/components/RightRail.tsx:[title="Open the focused plan review dialog."]',
  'src/components/RightRail.tsx::is([title="Pause auto-continuation (only user can pause)"],[title="Resume auto-continuation"])',
  'src/components/RightRail.tsx:[title="Mark build as complete — stops the auto-continuation loop. Use when the agent finished but did not call the completion tool itself."]',
  'src/components/UpdateBanner.tsx:role=button;name="Release notes"',
  'src/components/UpdateBanner.tsx:role=button;name="Install &amp; restart"',
  'src/components/settings/AboutTab.tsx:[data-debug-id="about-full-manual-link"]',
  'src/components/settings/AboutTab.tsx:[data-debug-id="surface-components-settings-abouttab-1"]',
  'src/components/settings/AboutTab.tsx:[data-debug-id="surface-components-settings-abouttab-10"]',
  'src/components/settings/AboutTab.tsx:[data-debug-id="surface-components-settings-abouttab-4"]',
  'src/components/settings/AboutTab.tsx:[data-debug-id="surface-components-settings-abouttab-5"]',
  'src/components/settings/AboutTab.tsx:[data-debug-id="surface-components-settings-abouttab-9"]',
  'src/components/settings/AboutTab.tsx:[title="Read bundled release notes"]',
  'src/components/settings/AboutTab.tsx:[title="Read the shellX features overview"]',
  'src/components/settings/AboutTab.tsx:[title="Read the shellX quick-start guide"]',
  'src/components/settings/AboutTab.tsx:[title="Read bundled third-party notices"]',
  'src/components/settings/AboutTab.tsx:role=button;name="Install &amp; restart"',
  'src/components/settings/DataTab.tsx:[id="data-delete-cancel"]',
  'src/components/settings/DataTab.tsx:[id="data-delete-confirm"]',
  'src/components/settings/DataTab.tsx:[title^="Delete the "][title$=" on disk + in localStorage"]',
  'src/components/settings/ConnectorsTab.tsx:[data-debug-id="surface-components-settings-connectorstab-3"]',
  'src/components/settings/ConnectorsTab.tsx:[data-debug-id="surface-components-settings-connectorstab-11"]',
  'src/components/settings/ConnectorsTab.tsx:[data-debug-id="surface-components-settings-connectorstab-21"]',
  'src/components/settings/ConnectorsTab.tsx:[id="connector-target"]',
  'src/components/settings/ConnectorsTab.tsx:[id="connector-allowed"]',
  'src/components/settings/ConnectorsTab.tsx:[id="connector-sim-connector"]',
  'src/components/settings/ConnectorsTab.tsx:[id="connector-sim-conversation"]',
  'src/components/settings/ConnectorsTab.tsx:[id="connector-sim-sender"]',
  'src/components/settings/ConnectorsTab.tsx:[id="connector-sim-text"]',
  'src/components/settings/ConnectorsTab.tsx:[id="connector-secret"]',
  'src/components/settings/ConnectorsTab.tsx:[aria-label="Cancel connector draft"]',
  'src/components/settings/ConnectorsTab.tsx:[title^="Send allowlisted "][title$=" messages to the active session"]',
  'src/components/settings/ConnectorsTab.tsx:role=button;name="Inbox"',
  'src/components/settings/ConnectorsTab.tsx:role=button;name="Live"',
  'src/components/settings/ConnectorsTab.tsx:role=button;name="New"',
  'src/components/settings/ConnectorsTab.tsx:role=button;name="Paused"',
  'src/components/settings/ConnectorsTab.tsx:role=button;name="Edit"',
  'src/components/settings/GeneralTab.tsx:[aria-label="Chat font size in pixels"]',
  'src/components/settings/GeneralTab.tsx:[aria-label="Use Black and warm theme"]',
  'src/components/settings/GeneralTab.tsx:[aria-label="Use Black theme"]',
  'src/components/settings/GeneralTab.tsx:[aria-label="Use Bright theme"]',
  'src/components/settings/GeneralTab.tsx:[data-debug-id="settings-density-comfortable"]',
  'src/components/settings/GeneralTab.tsx:[data-debug-id="settings-browser-download-folder"]',
  'src/components/settings/GeneralTab.tsx:[data-debug-id="settings-density-compact"]',
  'src/components/settings/GeneralTab.tsx:[data-debug-id="settings-density-default"]',
  'src/components/settings/GeneralTab.tsx:[title="Reset to default"]',
  'src/components/settings/VaultGrantsPanel.tsx:role=button;name="Refresh"',
  'src/components/settings/VaultGrantsPanel.tsx:role=button;name="Revoke"',
  'src/components/FilesPane.tsx::is([title="Attach handler unavailable"],[title="Attach selected files to the composer"])',
  'src/components/FilesPane.tsx:[aria-label^="Attach "]',
  'src/components/FilesPane.tsx:[aria-label^="Remove "]',
  'src/components/FilesPane.tsx:[aria-label="Clear selected files"]',
  'src/components/FilesPane.tsx:[data-debug-id="surface-components-filespane-7"]',
  'src/components/FilesPane.tsx:[data-debug-id="files-search-input"]',
  'src/components/FilesPane.tsx:[aria-label="Back to session folder"]',
  'src/components/FilesPane.tsx:[aria-label="Up one level"]',
  'src/components/FilePreviewModal.tsx:[id="file-preview-mode-code"]',
  'src/components/FilePreviewModal.tsx:[id="file-preview-mode-safe-render"]',
  'src/components/FilePreviewModal.tsx:[id="file-preview-run-work"]',
  'src/components/FindPopover.tsx:[title="Open this chat in a new tab (Enter)"]',
  'src/components/FindPopover.tsx:[data-debug-id="find-sessions-input"]',
  'src/components/FindPopover.tsx:[data-debug-id="surface-components-findpopover-1"]',
  'src/components/FindPopover.tsx:[data-debug-id="surface-components-findpopover-3"]',
  'src/components/FindPopover.tsx:[data-debug-id="surface-components-findpopover-4"]',
  'src/components/GoalPlanReviewModal.tsx:[aria-label="Review later"]',
  'src/components/GoalPlanReviewModal.tsx:[data-debug-id="surface-components-goalplanreviewmodal-4"]',
  'src/components/GoalPlanReviewModal.tsx:[data-debug-id="surface-components-goalplanreviewmodal-7"]',
  'src/components/GoalPlanReviewModal.tsx:[data-debug-id="surface-components-goalplanreviewmodal-9"]',
  'src/components/GoalPlanReviewModal.tsx:[placeholder="What should Grok change about this plan? (Ctrl+Enter to submit)"]',
  'src/components/GoalPlanReviewModal.tsx:role=button;name="Cancel"',
  'src/components/GoalPlanReviewModal.tsx:role=button;name="Request changes"',
  'src/components/GoalPlanReviewModal.tsx:role=button;name="Review later"',
  'src/components/HashAutocomplete.tsx:[data-debug-id="surface-components-hashautocomplete-1"]',
  'src/components/Header.tsx:[data-debug-id="header-shellx-browser"]',
  'src/components/Header.tsx:[data-debug-id="header-theme-toggle"]',
  'src/components/HeaderVaultRequestCenter.tsx:[data-debug-id="header-vault-request-center"]',
  'src/components/HeaderVaultRequestCenter.tsx:[data-debug-id="vault-request-generate-password"]',
  'src/components/HeaderVaultRequestCenter.tsx:[data-debug-id="vault-request-new-secret"]',
  'src/components/HeaderVaultRequestCenter.tsx:[data-debug-id="vault-request-open-vault"]',
  'src/components/LeftRail.tsx::is([title="Collapse all projects"],[title="Expand all projects"])',
  'src/components/LeftRail.tsx::is([title="Hide open chats — drop here to unfile"],[title="Show open chats — drop here to unfile"])',
  'src/components/LeftRail.tsx:[data-debug-id="left-past-chats-toggle"]',
  'src/components/PluginsModal.tsx::is([title="Cancel adding key (clears input)"],[title="Enter your API key inline"])',
  'src/components/PluginsModal.tsx::is([title="Collapse tier"],[title="Expand tier"])',
  'src/components/PluginsModal.tsx:[data-debug-id="plugins-vault-key-input"]',
  'src/components/PRCreateModal.tsx:[data-debug-id="pr-base-input"]',
  'src/components/PRCreateModal.tsx:[data-debug-id="pr-body-input"]',
  'src/components/PRCreateModal.tsx:[data-debug-id="pr-title-input"]',
  'src/components/PRCreateModal.tsx:[data-debug-id="surface-components-prcreatemodal-8"]',
  'src/components/PRCreateModal.tsx:[data-debug-id="surface-components-prcreatemodal-10"]',
  'src/components/PRCreateModal.tsx::is([title="Append the session transcript as an appendix"],[title="No transcript captured yet"])',
  'src/components/PRCreateModal.tsx:role=button;name="Cancel"',
  'src/components/PRCreateModal.tsx:role=button;name="Draft"',
  'src/components/settings/ShellxagentTab.tsx:[data-debug-id="surface-components-settings-shellxagenttab-1"]',
  'src/components/settings/ShellxagentTab.tsx:[data-debug-id="surface-components-settings-shellxagenttab-3"]',
  'src/components/ShellxSetupGuide.tsx:[data-debug-id="shellx-setup-guide-dismiss"]',
  'src/components/ShellxSetupGuide.tsx:[data-debug-id="shellx-setup-step-agents"]',
  'src/components/ShellxSetupGuide.tsx:[data-debug-id="shellx-setup-step-browser"]',
  'src/components/ShellxSetupGuide.tsx:[data-debug-id="shellx-setup-step-downloads"]',
  'src/components/ShellxSetupGuide.tsx:[data-debug-id="shellx-setup-step-requests"]',
  'src/components/ShellxSetupGuide.tsx:[data-debug-id="shellx-setup-step-vault"]',
  'src/components/ShellxBrowserApp.tsx:[data-debug-id="shellx-browser-personal-lock-notice-unlock"]',
  'src/components/ShellxBrowserApp.tsx:[data-debug-id="shellx-browser-personal-lock-overlay-pin"]',
  'src/components/ShellxBrowserApp.tsx:[data-debug-id="shellx-browser-personal-lock-overlay-unlock"]',
  'src/components/TasksPanel.tsx:[data-debug-id="tasks-filter-input"]',
  'src/components/TasksPanel.tsx:[data-debug-id="tasks-show-all-tabs-checkbox"]',
  'src/components/TasksPanel.tsx:[data-debug-id="tasks-show-completed-checkbox"]',
  'src/components/VaultPasswordGenerator.tsx:[data-debug-id="vault-password-generator-close"]',
  'src/components/VaultPasswordGenerator.tsx::is([aria-label="Hide generated password"],[aria-label="Reveal generated password"])',
  'src/components/VaultPasswordGenerator.tsx:[data-debug-id="surface-components-vaultpasswordgenerator-11"]',
  'src/components/VaultPasswordGenerator.tsx:[data-debug-id="surface-components-vaultpasswordgenerator-5"]',
  'src/components/VaultPasswordGenerator.tsx:[data-debug-id="vault-password-generator-length"]',
  'src/components/WorkPreviewPanel.tsx:[data-debug-id="surface-components-workpreviewpanel-3"]',
  'src/components/WorkPreviewPanel.tsx:[id="work-preview-refresh-state"]',
  'src/components/WorkPreviewPanel.tsx:[id="work-preview-doctor"]',
  'src/components/WorkPreviewPanel.tsx:[id="work-preview-open"]',
  'src/components/WorkPreviewPanel.tsx:[id="work-preview-frame-reload"]',
  'src/components/WorkPreviewPanel.tsx:[id="work-preview-viewport-phone"]',
  'src/components/WorkPreviewPanel.tsx:[id="work-preview-viewport-tablet"]',
  'src/components/WorkPreviewPanel.tsx:[id="work-preview-viewport-desktop"]',
  'src/components/WorkPreviewPanel.tsx:[id="work-preview-log-height-toggle"]',
  'src/components/PreviewCenter.tsx:[id="preview-center-file-mode"]',
  'src/components/PreviewCenter.tsx:[id="preview-center-work-mode"]',
  'src/components/WorkPreviewPanel.tsx:[id="work-preview-kind-auto"]',
  'src/components/WorkPreviewPanel.tsx:[id="work-preview-kind-expo"]',
  'src/components/WorkPreviewPanel.tsx:[id="work-preview-kind-static"]',
  'src/components/WorkPreviewPanel.tsx:[id="work-preview-kind-web"]',
  'src/components/WorkPreviewPanel.tsx:[id="work-preview-panel-open-external"]',
  'src/components/WorkPreviewPanel.tsx:[id="work-preview-restart"]',
  'src/components/WorkPreviewPanel.tsx:[id="work-preview-stage-open-external"]',
  'src/components/WorkPreviewPanel.tsx:[id="work-preview-stop"]',
  'src/components/settings/VaultTab.tsx:[data-debug-id="vault-resource-form-tab-profileCard"]',
  'src/components/settings/VaultTab.tsx:[data-debug-id="vault-resource-form-tab-secret"]',
  'src/components/settings/VaultTab.tsx:[data-debug-id="vault-resource-form-tab-stripeAgentWallet"]',
  'src/components/settings/VaultTab.tsx:[data-debug-id="surface-components-settings-vaulttab-45"]',
  'src/components/settings/VaultTab.tsx:[data-debug-id="surface-components-settings-vaulttab-48"]',
  'src/components/settings/VaultTab.tsx:[data-debug-id="surface-components-settings-vaulttab-57"]',
  'src/components/settings/VaultTab.tsx:[data-debug-id="surface-components-settings-vaulttab-59"]',
  'src/components/settings/VaultTab.tsx:[data-debug-id="vault-tab-grants"]',
  'src/components/settings/VaultTab.tsx:[data-debug-id="vault-tab-secrets"]',
  'src/components/settings/VaultTab.tsx:[data-debug-id="vault-tab-setup"]',
  'src/components/settings/VaultTab.tsx:[data-debug-id="vault-permission-browserFillAlways"]',
  'src/components/settings/VaultTab.tsx:[data-debug-id="vault-permission-toolUseAlways"]',
  'src/components/settings/VaultTab.tsx:[data-debug-id="vault-permission-userOnly"]',
  'src/components/settings/VaultTab.tsx:[data-debug-id="vault-permission-visible"]',
  'src/components/settings/VaultSetupPanel.tsx:[data-debug-id="shellx-vault-remember-device-setup"]',
  'src/components/settings/VaultSetupPanel.tsx:[data-debug-id="shellx-vault-change-setup"]',
  'src/components/settings/VaultSetupPanel.tsx:[data-debug-id="shellx-vault-confirm-passphrase"]',
  'src/components/settings/VaultSetupPanel.tsx:[data-debug-id="shellx-vault-forget-device"]',
  'src/components/settings/VaultSetupPanel.tsx:[data-debug-id="shellx-vault-master-passphrase"]',
  'src/components/settings/VaultSetupPanel.tsx:[data-debug-id="shellx-vault-recovery-confirm"]',
  'src/components/settings/VaultSetupPanel.tsx:[data-debug-id="shellx-vault-remember-device-enable"]',
  'src/components/settings/VaultSetupPanel.tsx:[data-debug-id="shellx-vault-remember-device-unlock"]',
  'src/components/settings/VaultSetupPanel.tsx:[data-debug-id="shellx-vault-remember-passphrase"]',
  'src/components/settings/VaultSetupPanel.tsx:[data-debug-id="shellx-vault-unlock"]',
  'src/components/settings/VaultSetupPanel.tsx:[data-debug-id="shellx-vault-unlock-passphrase"]',
  'src/components/settings/VaultSetupPanel.tsx:[placeholder="Access token"]',
  'src/components/settings/VaultSetupPanel.tsx:[placeholder="Repo"]',
  'src/components/settings/VaultSetupPanel.tsx:[placeholder="Server URL"]',
  'src/components/settings/VaultSetupPanel.tsx:role=button;name="Create recovery kit"',
  'src/components/settings/VaultSetupPanel.tsx:role=button;name="External"',
  'src/components/settings/VaultSetupPanel.tsx:role=button;name="Local"',
  'src/components/settings/VaultSetupPanel.tsx:role=input;name="Import existing ShellX secrets"',
  'src/components/VaultPanel.tsx:[aria-label="Vault master passphrase"]',
  'src/components/VaultPanel.tsx:[data-debug-id="surface-components-vaultpanel-5"]',
  'src/components/VaultPanel.tsx:[data-debug-id="vault-workspace-lock"]',
  'src/components/settings/VaultTab.tsx:[data-debug-id="vault-filter-input"]',
  'src/components/settings/VaultTab.tsx:[data-debug-id="vault-secret-key-input"]',
  'src/components/settings/VaultTab.tsx:[data-debug-id="vault-secret-value-input"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Address line 1"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Address line 2"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Allowed categories, comma-separated"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Allowed origins, comma-separated"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Budget summary"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Card label"]',
  'src/components/settings/VaultTab.tsx:[placeholder="City"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Company"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Country"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Email"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Full name"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Phone"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Postal code"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Region"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Role"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Stripe API secret ref"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Stripe account ref"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Stripe card ref"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Stripe cardholder ref"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Username"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Wallet label"]',
  'src/components/settings/VaultTab.tsx:[placeholder="Webhook signing secret ref"]',
  'src/components/settings/VaultTab.tsx:[placeholder="description visible to agents unless marked user-only"]',
  'src/lib/markdown-links.tsx:[data-debug-id="surface-lib-markdown-links-1"]',
  'src/lib/markdown-links.tsx:[data-debug-id="surface-lib-markdown-links-2"]',
  'src/components/LazySurface.tsx:role=button;name="Close"',
  'src/components/LazySurface.tsx:role=button;name="Retry"',
]);

export function supportsBoundedInstalledUiControl(assignment: Assignment): boolean {
  return UI_CONTROL_BOUNDED_INSTALLED_SURFACE_NAMES.has(assignment.surface.name);
}

export function assertBoundedInstalledUiControlAssignments(assignments: readonly Assignment[]): void {
  const unsupported = assignments.filter((assignment) => !supportsBoundedInstalledUiControl(assignment));
  if (unsupported.length > 0) {
    throw new Error(`bounded installed UI driver refuses non-allowlisted surfaces: ${unsupported.map((row) => row.surface.id).join(", ")}`);
  }
}
