use super::*;

// ───── net_fetch (allow-listed HTTP) ─────
//
// Design notes:
// * The allow-list is the single security boundary. Without it
// net_fetch would be an unbounded SSRF primitive — grok could
// fetch `http://169.254.169.254/...` on a cloud VM and lift
// instance metadata. Even with the list, callers should keep
// it tight; we ship a "common docs / package indices" default.
// * We default reqwest to rustls-tls + json features in Cargo.toml
// (already pulled in for the STT client). No openssl on Windows,
// no native-tls feature divergence per-platform.
// * Body cap: we stream `bytes_stream` so we never hold more
// than `max_bytes + chunk_size` in memory. On overflow we stop
// reading + flag `truncated=true` but still return what we got.
// * Method semantics: GET/HEAD allow an absent body; everything
// else requires `body` to be present and defaults Content-Type
// to `application/json` to match the spec sheet.
//
// Allow-list file shape:
// hosts = ["github.com", "*.example.com"]
// Globs use a leading `*` — `*.foo.bar` matches `a.foo.bar` and
// `x.y.foo.bar`. No leading-star match on the bare label is allowed
// (i.e. `*foo` is treated as a literal). Exact host match
// (no port handling — URL parser strips the port for host) takes
// precedence.
pub(super) const NET_FETCH_DEFAULT_MAX_BYTES: usize = 5_000_000;
pub(super) const NET_FETCH_HARD_MAX_BYTES: usize = 10 * 1024 * 1024;

/// Filesystem path for the allow-list. Lives under `~/.shellx`
/// alongside `vault.enc` — same parent dir, same lifecycle. Tests
/// override via the `GROK_SHELL_NET_ALLOW_FILE` env var to point at
/// a temp file without touching the user's real config.
pub(super) fn net_allow_file_path() -> PathBuf {
    if let Some(override_path) = std::env::var_os("GROK_SHELL_NET_ALLOW_FILE") {
        return PathBuf::from(override_path);
    }
    let home = std::env::var_os("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("/"));
    home.join(".shellx").join("net_allow.toml")
}

/// Default content for `net_allow.toml`. Created on first call if
/// the file doesn't exist. Tracks the original spec list from the
/// brief — adjust by editing the file or via the Settings UI later.
///
/// Loopback note (#383 M8, codebase audit 2026-05-20): bare loopback
/// hosts (`127.0.0.1`, `localhost`, `::1`) are NO LONGER blanket-
/// allowed — that turned net_fetch into a localhost port scanner.
/// shellX's own debug-api + MCP HTTP ports are auto-allowed at
/// request time (read from the OnceLock the binders populate), so
/// `net_fetch http://127.0.0.1:<debug-port>/health` still works without
/// a config entry. Other loopback ports (Ollama :11434, postgres :5432,
/// random dev servers) must be opted-in EXPLICITLY by adding a
/// `host:port` entry, e.g. `"127.0.0.1:11434"`.
const NET_ALLOW_DEFAULT_TOML: &str = "\
# ShellX host allow-list for the `net_fetch` MCP tool.
#
# Entries are host patterns: either an exact hostname (e.g.
# \"github.com\") or a glob with a leading star (e.g.
# \"*.githubusercontent.com\"). The leading-star form matches
# the bare domain only when the literal label is one segment.
#
# Loopback (127.0.0.1, localhost, ::1) requires an explicit
# `host:port` entry — e.g. `\"127.0.0.1:11434\"` to opt-in Ollama.
# shellX's own debug-api and MCP-HTTP ports are auto-allowed at
# request time, so they do NOT need to be listed here.
#
# Generated by net_fetch on first call.
hosts = [
  \"github.com\",
  \"raw.githubusercontent.com\",
  \"*.githubusercontent.com\",
  \"docs.rs\",
  \"crates.io\",
  \"api.anthropic.com\",
  \"*.xai-cdn.com\",
]
";

/// Parsed allow-list. Kept tiny so the TOML serde derive carries no
/// surprises and the round-trip stays deterministic.
#[derive(Deserialize, Debug, Clone, Default)]
pub(super) struct NetAllow {
    #[serde(default)]
    pub(super) hosts: Vec<String>,
}

/// Read (or initialise) the allow-list file. Returns the parsed
/// list. On first call the parent dir is created and the default
/// TOML written. Soft-fails: if the file is malformed we return
/// an empty list — that fails ALL requests, which is the safe
/// default. The dispatcher surfaces a structured error.
pub(super) fn load_net_allow() -> Result<NetAllow, String> {
    let path = net_allow_file_path();
    if !path.exists() {
        // mkdir -p the parent + drop the default.
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("net_fetch: failed to create {}: {}", parent.display(), e))?;
        }
        std::fs::write(&path, NET_ALLOW_DEFAULT_TOML)
            .map_err(|e| format!("net_fetch: failed to write {}: {}", path.display(), e))?;
    }
    let body = std::fs::read_to_string(&path)
        .map_err(|e| format!("net_fetch: failed to read {}: {}", path.display(), e))?;
    let parsed: NetAllow = toml::from_str(&body)
        .map_err(|e| format!("net_fetch: malformed {}: {}", path.display(), e))?;
    Ok(parsed)
}

/// Match a hostname against one pattern. Exact: full equality.
/// Glob: pattern starts with `*.` — the host must end with the
/// rest (including the leading `.`), and the prefix before that
/// must be non-empty (so `foo.bar` does NOT match `*.foo.bar`).
pub(super) fn host_matches_pattern(host: &str, pat: &str) -> bool {
    let host = host.to_ascii_lowercase();
    let pat = pat.to_ascii_lowercase();
    if let Some(suffix) = pat.strip_prefix("*.") {
        // suffix is e.g. "githubusercontent.com"; host must end with
        // ".githubusercontent.com" and have at least one label before.
        let dotted = format!(".{}", suffix);
        if host == suffix {
            // `*.foo.bar` does NOT match bare `foo.bar`.
            return false;
        }
        return host.ends_with(&dotted);
    }
    host == pat
}

pub(super) fn parse_obscure_ipv4_piece(piece: &str) -> Option<u32> {
    if piece.is_empty() {
        return None;
    }
    let (digits, radix) = if let Some(rest) = piece
        .strip_prefix("0x")
        .or_else(|| piece.strip_prefix("0X"))
    {
        (rest, 16)
    } else if piece.len() > 1 && piece.starts_with('0') {
        (&piece[1..], 8)
    } else {
        (piece, 10)
    };
    if digits.is_empty() {
        return None;
    }
    u32::from_str_radix(digits, radix).ok()
}

pub(super) fn parse_obscure_ipv4(host: &str) -> Option<Ipv4Addr> {
    if !host.bytes().all(|b| {
        b.is_ascii_digit()
            || b == b'.'
            || b == b'x'
            || b == b'X'
            || (b'a'..=b'f').contains(&b)
            || (b'A'..=b'F').contains(&b)
    }) {
        return None;
    }
    let parts: Vec<u32> = host
        .split('.')
        .map(parse_obscure_ipv4_piece)
        .collect::<Option<Vec<_>>>()?;
    let value = match parts.as_slice() {
        [a] => *a,
        [a, b] if *a <= 0xff && *b <= 0x00ff_ffff => (*a << 24) | *b,
        [a, b, c] if *a <= 0xff && *b <= 0xff && *c <= 0xffff => (*a << 24) | (*b << 16) | *c,
        [a, b, c, d] if *a <= 0xff && *b <= 0xff && *c <= 0xff && *d <= 0xff => {
            (*a << 24) | (*b << 16) | (*c << 8) | *d
        }
        _ => return None,
    };
    Some(Ipv4Addr::from(value))
}

pub(super) fn parse_host_ip_literal(host: &str) -> Option<IpAddr> {
    let host = host.trim_matches(['[', ']']).trim_end_matches('.');
    host.parse::<IpAddr>()
        .ok()
        .or_else(|| parse_obscure_ipv4(host).map(IpAddr::V4))
}

pub(super) fn restricted_ip_reason(ip: IpAddr) -> Option<&'static str> {
    match ip {
        IpAddr::V4(v4) => {
            if v4.is_loopback() {
                Some("loopback")
            } else if v4.is_link_local() || v4 == Ipv4Addr::new(169, 254, 169, 254) {
                Some("link-local")
            } else if (v4.octets()[0] == 100) && ((v4.octets()[1] & 0b1100_0000) == 64) {
                Some("shared-address")
            } else if v4.is_private() {
                Some("private")
            } else if v4.is_unspecified() {
                Some("unspecified")
            } else {
                None
            }
        }
        IpAddr::V6(v6) => {
            if v6.is_loopback() {
                Some("loopback")
            } else if (v6.segments()[0] & 0xffc0) == 0xfe80 {
                Some("link-local")
            } else if (v6.segments()[0] & 0xfe00) == 0xfc00 {
                Some("unique-local")
            } else if v6.is_unspecified() {
                Some("unspecified")
            } else if matches!(v6.to_ipv4_mapped(), Some(v4) if restricted_ip_reason(IpAddr::V4(v4)).is_some())
            {
                Some("ipv4-mapped")
            } else {
                None
            }
        }
    }
}

pub(super) async fn resolve_public_dns_targets(
    parsed_url: &reqwest::Url,
) -> Result<Option<Vec<SocketAddr>>, String> {
    let host = parsed_url
        .host_str()
        .ok_or_else(|| "net_fetch: no host in url".to_string())?;
    let host_lc = host.to_ascii_lowercase();
    if host_lc == "localhost" || parse_host_ip_literal(&host_lc).is_some() {
        return Ok(None);
    }
    let port = parsed_url
        .port_or_known_default()
        .ok_or_else(|| "net_fetch: url without resolvable port".to_string())?;
    let addrs = tokio::net::lookup_host((host, port))
        .await
        .map_err(|e| format!("net_fetch: DNS lookup for {} failed: {}", host, e))?;
    let addrs: Vec<SocketAddr> = addrs.collect();
    if addrs.is_empty() {
        return Err(format!(
            "net_fetch: DNS lookup for {} returned no addresses",
            host
        ));
    }
    for addr in &addrs {
        let ip = addr.ip();
        if let Some(reason) = restricted_ip_reason(ip) {
            return Err(format!(
                "net_fetch: host {} resolved to restricted IP {} ({})",
                host, ip, reason
            ));
        }
    }
    Ok(Some(addrs))
}

/// Return Ok() if the URL's host (and port, for loopback) is on the
/// allow-list; Err(structured message) otherwise.
///
/// Loopback rule (tightened, #383 M8 — codebase audit 2026-05-20):
/// loopback hosts (`127.0.0.1`, `localhost`, `::1`) used to be
/// blanket-allowed. That let any agent probe random local services
/// (Ollama :11434, postgres :5432, dev servers, etc) — turning
/// net_fetch into a localhost scanner. Now we require the loopback
/// port to be either:
/// (a) shellX's own bound debug-api port (from
/// `crate::debug_api::BOUND_DEBUG_API_PORT`, set by agent A's
/// OnceLock in #379 M4), OR
/// (b) shellX's bound MCP-HTTP port (`BOUND_MCP_HTTP_PORT`), OR
/// (c) an explicit `host:port` entry in `net_allow.toml` (e.g.
/// `"127.0.0.1:11434"` to opt-in Ollama).
/// Bare host entries (`"127.0.0.1"` with no port) intentionally do
/// NOT cover loopback ports any more — that was the SSRF foothold.
///
/// Non-loopback hosts keep the old host-only matching (port is not
/// considered) — that boundary was already correct.
pub(super) fn host_is_allowed(parsed_url: &reqwest::Url, allow: &NetAllow) -> Result<(), String> {
    let host = parsed_url
        .host_str()
        .ok_or_else(|| "no host in url".to_string())?;
    // Lowercase host once for all comparisons below.
    let host_lc = host.to_ascii_lowercase();
    let host_ip = parse_host_ip_literal(&host_lc);
    let is_loopback = host_ip
        .map(|ip| {
            matches!(
                restricted_ip_reason(ip),
                Some("loopback") | Some("ipv4-mapped")
            )
        })
        .unwrap_or_else(|| matches!(host_lc.as_str(), "localhost"));

    if is_loopback {
        // Default loopback port per scheme (80/443) when the URL omits one.
        let port = parsed_url
            .port_or_known_default()
            .ok_or_else(|| "loopback url without resolvable port".to_string())?;

        // (a) + (b): shellX's own bound ports.
        let bound_debug = crate::debug_api::BOUND_DEBUG_API_PORT.get().copied();
        let bound_mcp = crate::debug_api::BOUND_MCP_HTTP_PORT.get().copied();
        if Some(port) == bound_debug || Some(port) == bound_mcp {
            return Ok(());
        }

        // (c): explicit `host:port` entry. We require the full
        // `host:port` form for loopback — bare `127.0.0.1` does NOT
        // satisfy. Patterns are exact-match in this scope (no glob),
        // since globs over numeric ports add confusion without value.
        let needle = format!("{}:{}", host_lc, port);
        if allow.hosts.iter().any(|p| p.to_ascii_lowercase() == needle) {
            return Ok(());
        }
        return Err(format!(
            "net_fetch: loopback {}:{} not in net_allow — add '{}://{}:{}' explicitly",
            host,
            port,
            parsed_url.scheme(),
            host,
            port
        ));
    }

    if let Some(ip) = host_ip {
        if let Some(reason) = restricted_ip_reason(ip) {
            return Err(format!(
                "net_fetch: restricted IP literal {} ({}) is not allowed",
                host, reason
            ));
        }
    }

    // Non-loopback: host-only pattern matching against allow-list.
    if allow
        .hosts
        .iter()
        .any(|p| host_matches_pattern(&host_lc, p))
    {
        Ok(())
    } else {
        Err(format!("host not allow-listed: {}", host))
    }
}

/// `net_fetch` tool body. See module-level notes for the contract.
pub(super) async fn tool_net_fetch(args: Value) -> Result<Value, String> {
    use reqwest::Method;

    // ── arg parsing ──
    let url = args
        .get("url")
        .and_then(|v| v.as_str())
        .ok_or("net_fetch: missing 'url'")?
        .to_string();
    let method_str = args
        .get("method")
        .and_then(|v| v.as_str())
        .unwrap_or("GET")
        .to_ascii_uppercase();
    let timeout_ms = args
        .get("timeout_ms")
        .and_then(|v| v.as_u64())
        .unwrap_or(30_000);
    let max_bytes = args
        .get("max_bytes")
        .and_then(|v| v.as_u64())
        .unwrap_or(NET_FETCH_DEFAULT_MAX_BYTES as u64);
    if max_bytes > NET_FETCH_HARD_MAX_BYTES as u64 {
        return Err(format!(
            "net_fetch: max_bytes {} exceeds hard cap {}",
            max_bytes, NET_FETCH_HARD_MAX_BYTES
        ));
    }
    let max_bytes = max_bytes as usize;
    let body_arg = args
        .get("body")
        .and_then(|v| v.as_str())
        .map(|s| s.to_string());
    let headers_arg = args.get("headers").cloned();

    // ── URL + host gate ──
    let parsed_url =
        reqwest::Url::parse(&url).map_err(|e| format!("net_fetch: bad url {}: {}", url, e))?;
    let host = parsed_url
        .host_str()
        .ok_or_else(|| format!("net_fetch: no host in url {}", url))?
        .to_string();
    let allow = load_net_allow()?;
    if let Err(msg) = host_is_allowed(&parsed_url, &allow) {
        // Structured error envelope, NOT an Err — the spec wants the
        // call to return cleanly with `{error}` and no HTTP attempt.
        return Ok(json!({
            "error": msg,
            "host": host,
            "url": url,
            "made_request": false,
        }));
    }
    let resolved_addrs = match resolve_public_dns_targets(&parsed_url).await {
        Ok(addrs) => addrs,
        Err(msg) => {
            return Ok(json!({
                "error": msg,
                "host": host,
                "url": url,
                "made_request": false,
            }));
        }
    };

    // ── method + body validation ──
    let method = Method::from_bytes(method_str.as_bytes())
        .map_err(|_| format!("net_fetch: unsupported method {}", method_str))?;
    let needs_body = matches!(
        method,
        Method::POST | Method::PUT | Method::PATCH | Method::DELETE
    );
    if needs_body && body_arg.is_none() {
        return Err(format!(
            "net_fetch: method {} requires a 'body' argument",
            method
        ));
    }

    // ── build the request ──
    // F-02 HIGH (codebase audit, 2026-05-20): disable reqwest's default
    // 10-redirect follow policy. An allow-listed `github.com` URL that
    // 302s to `http://127.0.0.1:<debug-port>/state/...` or
    // `http://169.254.169.254/...` (cloud metadata) bypasses our host
    // allow-list check (initial URL only). Reject all 3xx — caller
    // gets the redirect target in the body/Location header and can
    // re-validate via a fresh net_fetch call.
    let mut client_builder = reqwest::Client::builder()
        .timeout(Duration::from_millis(timeout_ms))
        .redirect(reqwest::redirect::Policy::none());
    if let Some(addrs) = resolved_addrs.as_deref() {
        client_builder = client_builder.resolve_to_addrs(&host, addrs);
    }
    let client = client_builder
        .build()
        .map_err(|e| format!("net_fetch: client build failed: {}", e))?;
    let mut req = client.request(method.clone(), parsed_url);

    // User-supplied headers. Track whether Content-Type was set.
    let mut user_supplied_ct = false;
    if let Some(Value::Object(map)) = headers_arg {
        for (k, v) in map {
            if let Some(vs) = v.as_str() {
                if k.eq_ignore_ascii_case("content-type") {
                    user_supplied_ct = true;
                }
                req = req.header(k, vs);
            }
        }
    }
    // Body + default Content-Type for body-bearing methods.
    if let Some(b) = body_arg {
        if needs_body && !user_supplied_ct {
            req = req.header(reqwest::header::CONTENT_TYPE, "application/json");
        }
        req = req.body(b);
    }

    // ── execute ──
    let resp = req
        .send()
        .await
        .map_err(|e| format!("net_fetch: request failed: {}", e))?;
    let status = resp.status().as_u16();
    let content_type = resp
        .headers()
        .get(reqwest::header::CONTENT_TYPE)
        .and_then(|v| v.to_str().ok())
        .unwrap_or("")
        .to_string();
    // Response headers as a flat string-map.
    let mut header_map = serde_json::Map::new();
    for (name, value) in resp.headers().iter() {
        if let Ok(s) = value.to_str() {
            header_map.insert(name.as_str().to_string(), Value::String(s.to_string()));
        }
    }

    // ── body stream with max_bytes cap ──
    // We use reqwest::Response::chunk instead of bytes_stream to
    // avoid pulling in futures-util as a direct dep — chunk returns
    // Ok(None) when the body is fully consumed, matching the cap loop
    // structure we want.
    let mut resp = resp;
    let mut buf: Vec<u8> = Vec::new();
    let mut truncated = false;
    while let Some(chunk) = resp
        .chunk()
        .await
        .map_err(|e| format!("net_fetch: body read failed: {}", e))?
    {
        if buf.len() + chunk.len() > max_bytes {
            let take = max_bytes.saturating_sub(buf.len());
            buf.extend_from_slice(&chunk[..take]);
            truncated = true;
            break;
        }
        buf.extend_from_slice(&chunk);
    }
    let body_bytes = buf.len();
    // Body as UTF-8 — lossy decode so a binary payload doesn't blow up
    // the response. Callers needing raw bytes should add a base64 flag.
    let body_text = String::from_utf8_lossy(&buf).to_string();

    Ok(json!({
        "status": status,
        "headers": Value::Object(header_map),
        "body": body_text,
        "body_bytes": body_bytes,
        "content_type": content_type,
        "truncated": truncated,
    }))
}
